name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Publish nuget
      run: dotnet nuget push "MyBaseLibrary/bin/Release/MyBaseLibrary.*.nupkg" --source https://nuget.pkg.github.com/jonnybi --api-key ${{github.token}} --skip-duplicate --no-symbols true
